# Generated by Django 3.2.7 on 2021-09-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('money_amount', models.IntegerField()),
                ('card_number', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
